CUDA_VISIBLE_DEVICES='0,1,2,3' python3 -m trainer.distribute --script main.py --dataset_name indictts \
    --language ta \
    --speaker male \
    --max_audio_len 441000 \
    --max_text_len 400 \
    --model aligntts \
    --use_speaker_embedding f \
    --batch_size 16 \
    --batch_size_eval 16 \
    --batch_group_size 5 \
    --epochs 5000 \
    --mixed_precision t \
    --run_description "aligntts_ta_male"