CUDA_VISIBLE_DEVICES='0,1,2,3' python3 -m trainer.distribute --script main.py --dataset_name indictts \
    --language ta \
    --speaker male \
    --use_speaker_embedding f \
    --model fastpitch \
    --batch_size 8 \
    --batch_size_eval 8 \
    --batch_group_size 5 \
    --max_audio_len 441000 \
    --max_text_len 400 \
    --epochs 10000 \
    --mixed_precision f \
    --run_description "fastpitch_ta_male"