python3 main.py --dataset_name indictts \
    --language ta \
    --speaker all \
    --max_audio_len 441000 \
    --max_text_len 400 \
    --model fastpitch \
    --hidden_channels 512 \
    --use_speaker_embedding t \
    --use_d_vector_file f \
    --use_speaker_encoder_as_loss f \
    --use_ssim_loss f \
    --use_aligner t \
    --use_pre_computed_alignments f \
    --batch_size 32 \
    --batch_size_eval 32 \
    --batch_group_size 0 \
    --epochs 5000 \
    --aligner_epochs 5000 \
    --mixed_precision t