python3 main.py --dataset_name indictts \
    --language ta \
    --speaker all \
    --max_audio_len 441000 \
    --max_text_len 400 \
    --model fastpitch \
    --hidden_channels 512 \
    --use_speaker_embedding t \
    --use_d_vector_file f \
    --use_speaker_encoder_as_loss f \
    --use_ssim_loss t \
    --use_aligner t \
    --use_pre_computed_alignments f \
    --batch_size 32 \
    --batch_size_eval 32 \
    --batch_group_size 0 \
    --epochs 2500 \
    --aligner_epochs 2500 \
    --lr 0.0001 \
    --lr_scheduler StepLR \
    --lr_scheduler_warmup_steps 4000 \
    --lr_scheduler_step_size 50000 \
    --mixed_precision t