CUDA_VISIBLE_DEVICES='0' python3 main.py --dataset_name googletts \
    --language ta \
    --speaker all \
    --max_audio_len 441000 \
    --max_text_len 400 \
    --model fastpitch \
    --hidden_channels 512 \
    --use_speaker_embedding f \
    --use_d_vector_file t \
    --d_vector_file output_speaker_encoder/pretrained/yourtts_d_vectors.pth \
    --d_vector_dim 512 \
    --speaker_encoder_model_path output_speaker_encoder/pretrained/yourtts_model.pth.tar \
    --speaker_encoder_config_path output_speaker_encoder/pretrained/yourtts_config.json \
    --use_speaker_encoder_as_loss t \
    --vocoder_path output_vocoder/store/ta/hifigan_multi/checkpoint_400000.pth \
    --vocoder_config_path output_vocoder/store/ta/hifigan_multi/config.json \
    --use_pre_computed_alignments f \
    --batch_size 2 \
    --batch_size_eval 2 \
    --batch_group_size 0 \
    --epochs 5000 \
    --mixed_precision t \
    --run_description "fastpitch_all_googletts"